### ISSUE TITLE
Requires visual studio

### ISSUE THREAD

**Issue by MrsTonedOne** [tgstation/BSQL#1]
This is c++ land baby, real programmers program in notepad++ and/or vim!

It is unacceptable that the library manager to manage 1 library requires a graphical ide to work on windows.

**Comment by Cyberboss** [comment]
Cmake should work fine on linux provided you have the libmaridb-dev package for your system. Currently struggling trying to get travis to compile it manually though since it's not in trusty.

**Comment by MrsTonedOne** [comment]
i mean for windows.

I use notepad++ tied in to the standalone cl.exe package as my primary dev environment but the shit for vcpkg says it requires the full blown visual studio bullshit

**Comment by Cyberboss** [comment]
afaddc94ff27f8d892926867601a3ece6ff38837 and 5aae514315013215f5ba57a7f22fbc20216a9ddb

**Comment by ras0219-msft** [comment]
Vcpkg does work with just the Visual Studio build tools -- if it doesn't that's definitely a bug and I'd appreciate a bug report at https://github.com/Microsoft/vcpkg!

**Comment by MrsTonedOne** [comment]
it says right there in the readme that it requires visual studio so the bug is in your documentation.

Also i can't submit a bug report 
![image](https://user-images.githubusercontent.com/7069733/41168804-db470780-6afb-11e8-9db2-fdba0978e795.png)

I got banned from the microsoft org for not liking windows 10.
